import fs from 'node:fs/promises';
import path from 'node:path';
export const escapeHTML = value => String(value ?? '').replace(/[&<>"']/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#39;' }[c]));
const names = {
  'horizontal-scroll': 'גלילה אופקית', 'clipped-document': 'חשד לתוכן חתוך בגבול העמוד', 'image-unsettled': 'טעינת תמונה טרם הושלמה', 'outside-viewport': 'רכיב חורג מהמסך', 'text-clipping': 'חשד לטקסט חתוך',
  'image-broken': 'תמונה שלא נטענה', 'image-blocked': 'תמונה נחסמה בסביבת הבדיקה', 'image-alt-missing': 'חסר מאפיין alt', 'form-label-missing': 'שדה ללא תווית מזוהה',
  'button-name-missing': 'כפתור ללא שם מזוהה', 'keyboard-unreachable': 'רכיב פעולה אינו נגיש ב־Tab', 'positive-tabindex': 'סדר מיקוד ידני',
  'heading-h1': 'מבנה כותרת ראשית לבדיקה', 'heading-skip': 'דילוג ברמת כותרת', 'language-missing': 'חסרה שפת מסמך', 'rtl-direction': 'כיוון מסמך עברי לבדיקה',
  'focus-invisible': 'המיקוד אינו נראה במסך', 'focus-indicator': 'חיווי מיקוד לבדיקה', 'javascript-error': 'שגיאת JavaScript', 'console-error': 'שגיאה בקונסול',
  'http-error': 'תשובת HTTP שגויה', 'request-failed': 'בקשת רשת נכשלה', 'broken-link': 'קישור פנימי שבור', 'broken-fragment': 'עוגן חסר בעמוד',
  'scenario-failed': 'תרחיש נכשל', 'visual-change': 'שינוי מול תמונת ייחוס', 'sitemap-error': 'מפת האתר לא נבדקה', 'page-check-error': 'בדיקת עמוד לא הושלמה',
  'baseline-unusable': 'תמונת ייחוס אינה תקפה להשוואה', 'link-unverified': 'קישור לא אומת', 'no-pages': 'לא נסרקו עמודים', 'dom-limit': 'מגבלת רכיבים',
};
const severity = { critical: 'קריטית', high: 'גבוהה', medium: 'בינונית', low: 'נמוכה', info: 'מידע' };
const visualNames = { 'no-approved-baseline': 'אין ייחוס מאושר — ההשוואה לא בוצעה', matched: 'בתוך סף ההבדל שהוגדר', changed: 'נמצא הבדל — לבדיקה אנושית', disabled: 'השוואה מושבתת', 'invalid-baseline': 'ייחוס לא תקף', 'incompatible-baseline': 'סביבת צילום שונה' };
const e = escapeHTML;
const localLink = (file, label) => file && /^(screenshots\/)[a-zA-Z0-9._/-]+$/.test(file) && !file.includes('..') ? `<a href="${e(file)}" target="_blank" rel="noopener">${e(label)}</a>` : '';
export async function writeReport(r, outDir) {
  const observed = r.findings.filter(f => f.certainty !== 'suspected'), suspects = r.findings.length - observed.length;
  const rows = r.findings.map(f => `<article class="finding" data-level="${e(f.severity)}" data-certainty="${e(f.certainty)}"><div class="row"><span class="badge ${e(f.severity)}">${e(severity[f.severity])}</span><span class="muted">${e(f.id)} · ${f.certainty === 'suspected' ? 'חשד לבדיקה אנושית' : 'ממצא אוטומטי'}</span></div><h3>${e(names[f.check] || f.check)}</h3><p class="location"><bdi>${e(f.page)}</bdi> · ${e(f.viewport?.width || 'כללי')}px · ${e(f.state)}</p><div class="row">${localLink(f.screenshot, 'צילום מסך')}${localLink(f.evidence?.diff, 'תמונת הבדלים')}${localLink(f.evidence?.baseline, 'תמונת ייחוס')}</div><details><summary>ראיות וצעדי שחזור</summary><pre dir="ltr">${e(JSON.stringify({ check: f.check, selector: f.selector, ...f.evidence }, null, 2))}</pre><ol>${f.reproduction.map(x => `<li>${e(x)}</li>`).join('')}</ol></details></article>`).join('');
  const html = `<!doctype html><html lang="he" dir="rtl"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>דוח בדיקת אתר · RTL QA</title><style>
  :root{font-family:Arial,"Segoe UI",sans-serif;color:#182f35;background:#f3f5f4;font-size:16px;line-height:1.65}*{box-sizing:border-box}body{margin:0}header{background:#103b42;color:white;padding:38px max(24px,calc((100vw - 1120px)/2))}header p{color:#c9dedb;margin-bottom:0}.brand{font-size:12px;letter-spacing:2px;color:#8ae0cb}h1{font-size:clamp(28px,5vw,42px);line-height:1.2;margin:14px 0}h2{margin-top:32px;font-size:23px}h3{margin:8px 0;font-size:20px}main{max-width:1168px;margin:0 auto;padding:24px}a{color:#006956;text-underline-offset:3px}.stats{display:grid;grid-template-columns:repeat(4,1fr);gap:12px;margin:-1px 0 24px}.stat{border-bottom:3px solid #147c70;background:white;padding:20px}.stat strong{display:block;font-size:32px;line-height:1.2}.muted{color:#536a70;font-size:14px}.notice{border-inline-start:4px solid #c38828;background:#fff9e9;padding:16px 20px}.notice p{margin:4px 0}.finding{background:white;border:1px solid #d5e0dd;border-radius:4px;padding:20px;margin:12px 0}.row{display:flex;gap:14px;align-items:center;flex-wrap:wrap}.badge{font-size:12px;padding:3px 10px;border-radius:3px;background:#e8efed}.high,.critical{background:#ffe4df;color:#8c281b}.medium{background:#fff0c7;color:#735012}.location{font-size:14px;overflow-wrap:anywhere;color:#536a70}details{margin-top:14px}summary{cursor:pointer;color:#175c59}pre{background:#f3f6f5;padding:14px;white-space:pre-wrap;overflow-wrap:anywhere;font-size:12px;text-align:left}table{border-collapse:collapse;width:100%;background:white}th,td{text-align:right;padding:12px;border-bottom:1px solid #d5e0dd;vertical-align:top;overflow-wrap:anywhere}th{background:#e5edea}.table{overflow:auto}button,select{font:inherit;padding:8px 12px;border:1px solid #a0b7b0;border-radius:3px;background:white;color:#183c39}button{cursor:pointer}footer{margin:40px 0;color:#536a70;font-size:14px}bdi{overflow-wrap:anywhere}img{max-width:100%}@media(max-width:620px){.stats{grid-template-columns:repeat(2,1fr)}main{padding:16px}.stat{padding:14px}th,td{min-width:100px}header{padding:28px 20px}}@media print{header{color:#182f35;background:white}.filters{display:none}.finding{break-inside:avoid}}
  </style></head><body><header><div class="brand">RTL / SITE QA</div><h1>בדיקת האתר, עם ראיות.</h1><p><bdi>${e(r.baseURL)}</bdi><br>${e(r.runId)} · Chromium ${e(r.browser || 'לא הופעל')}</p></header><main>
  <div class="stats"><div class="stat"><strong>${r.coverage.urlsVisited}</strong>עמודים</div><div class="stat"><strong>${r.pages.length}</strong>בדיקות עמוד ורוחב</div><div class="stat"><strong>${observed.length}</strong>ממצאים אוטומטיים</div><div class="stat"><strong>${suspects}</strong>חשדות לבדיקה</div></div>
  <div class="notice"><p><strong>${r.exitCode === 2 ? 'הריצה לא הושלמה — קוד 2' : r.exitCode === 1 ? 'נמצאו ממצאים שחוצים את סף הכישלון — קוד 1' : 'לא נחצה סף הכישלון — קוד 0'}</strong> · סף: ${e(r.settings.failOn)}</p><p>הדוח מכסה רק את העמודים, הרוחבים והתרחישים המפורטים. הוא אינו אישור לנגישות מלאה, לאבטחה או להתאמה לנטפרי. חשדות חזותיים אינם מכשילים את CI.</p>${r.fatal ? `<p>${e(r.fatal)}</p>` : ''}</div>
  <h2>ממצאים</h2><div class="row filters"><label>חומרה <select id="level"><option value="all">הכול</option>${Object.entries(severity).map(([k,v]) => `<option value="${k}">${v}</option>`).join('')}</select></label><label>סוג <select id="certainty"><option value="all">הכול</option><option value="observed">ממצא אוטומטי</option><option value="suspected">חשד לבדיקה</option></select></label><span id="visible-count" role="status"></span></div>${rows || '<p>לא נמצאו ממצאים בבדיקות שבוצעו.</p>'}
  <h2>כיסוי וצילומי מסך</h2><div class="table"><table><thead><tr><th>עמוד / רוחב</th><th>סטטוס ותרחישים</th><th>השוואה חזותית</th></tr></thead><tbody>${r.pages.map(p => `<tr><td><bdi>${e(p.url)}</bdi><br>${p.viewport.width} × ${p.viewport.height}</td><td>${p.status === 'completed' ? 'הבדיקה הסתיימה' : 'בדיקה חלקית'}<br>${p.scenarios.map(s => `${e(s.name)}: ${s.status === 'passed' ? 'עבר' : 'נכשל'}`).join('<br>')}</td><td>${p.screenshots.map(s => `${localLink(s.file, s.state)} · ${e(visualNames[s.visual.status])}<br><small dir="ltr">${e(s.key)}</small>`).join('<br>')}</td></tr>`).join('')}</tbody></table></div>
  <h2>מה לא נבדק, ומה נחסם</h2><p>נבדקו ${r.coverage.linksChecked} קישורים ייחודיים ו־${r.coverage.sitemapDocuments} קובצי sitemap. נרשמו ${r.coverage.blockedRequests} אירועי חסימה או הדמיה. בזמן תרחישים, כל קריאת רשת חסומה מלבד תשובות דמה שהוגדרו במפורש.</p><p>מגבלות שהופעלו: ${e(r.coverage.truncated.join(', ') || 'לא הופעלו')}. יש לבדוק ידנית קיצורי טקסט מכוונים, איכות טקסט חלופי, סדר קריאה, קורא מסך, ניגודיות ומיקוד בכל המסלולים.</p>
  <details><summary>הגדרות, חריגות וחסימות</summary><pre dir="ltr">${e(JSON.stringify({ settings: r.settings, skipped: r.skipped, network: r.pages.map(p => ({ page: p.url, width: p.viewport.width, blocked: p.blocked })) }, null, 2))}</pre></details><footer><a href="report.json">הורדת הדוח כ־JSON</a> · צילומים משקפים את סביבת הבדיקה ואת החסימות שהוגדרו. אין תמונת ייחוס מאושרת? ההשוואה החזותית אינה מוכרעת.</footer></main>
  <script>const update=()=>{let n=0;document.querySelectorAll('.finding').forEach(el=>{el.hidden=!(level.value==='all'||el.dataset.level===level.value)||!(certainty.value==='all'||el.dataset.certainty===certainty.value);if(!el.hidden)n++});document.getElementById('visible-count').textContent=n+' ממצאים מוצגים'};const level=document.getElementById('level'),certainty=document.getElementById('certainty');level.addEventListener('change',update);certainty.addEventListener('change',update);update();</script></body></html>`;
  await fs.mkdir(outDir, { recursive: true });
  await fs.writeFile(path.join(outDir, 'report.json'), JSON.stringify(r, null, 2));
  await fs.writeFile(path.join(outDir, 'report.html'), html);
}
